
export default{
    registerUser:'/register',
    loginUser:'/login',
    verifyOtp:'/verifyOtp',
    googleAuth:'/googleAuth',
    resendOtp:'/resendOtp',
    savePost:'/savePost',
    getUserPost:'/getUserPost',
    editProfile:'/editProfile',
    getUserDetails:'/getUserDetails',
    getAllUsers:'/getAllUsers',
    followUser:'/followToggle',
    userFeedPost:'/userFeedPost',
    loadChat:'/chat',
    forgotPassword:'/forgotPassword',
    updatePassword:'/updatePassword',
    postDelete:'/deletePost',
    editPost:'/editPost',
    sendMessage:'/chat/message',
    following:'/following',
    addComment:'/addComment',
    loadComments:'/fetchAllComments',
    addReply:'/addReply',
    toggleLike:'/likePost',
    likeStatus:'/likeStatus',
    comments:'/comments',
    reportPost:'/report',
    upload:'/chat/upload',
    getSignedUrl:'/chat/signed_url',
    fileUpload:'/chat/fileUpload',
    getNotification:'/notification',
    sharedPost:'/chat/sharedPost',
    savedPost:'/savedPost',
    getSavedPosts:'/getSavedPosts',
    verifiedTag:"/verifiedTag"

}